execute pathogen#infect()
filetype plugin indent on

syntax enable "enable syntax highlighting

set background=dark "dark colorscheme

let mapleader=" " "changing <Leader> to a space (default is \)

set nocompatible "vim doesn't have to act like vi
set copyindent
set preserveindent

"Tab Settings
set shiftwidth=4 "affects how automatic indentation works as well as the >>, << or ==
set tabstop=4 "number of visual spaces per <Tab>
set smarttab

set number "show line numbers
set relativenumber "show number of lines away each line is from current line

set autoindent "enable automatic indentation

"turn on special characters
set listchars=eol:$,tab:>-,trail:~,extends:>,precedes:<
set list

"boilerplate for class comments using the ( // Mark: - Comment here ) format
nnoremap <leader>comment :read $HOME/.vim/boilerplates/comment<cr>kdd<cr>

"allows for quick vimrc editing/reloading of vimrc
nnoremap <leader>en :vsplit $MYVIMRC<cr>
nnoremap <leader>sv :source $MYVIMRC<cr>

"tp means 'TemPlate'. The following are boilerplates for a couple of languages.
autocmd FileType java nnoremap <leader>tp :read $HOME/.vim/boilerplates/java<cr>kdd<cr>/{<cr>:nohl<cr>o
autocmd FileType html nnoremap <leader>tp :read $HOME/.vim/boilerplates/html<cr>kkd<cr>/title<cr>:nohl<cr>f>a
autocmd FileType c    nnoremap <leader>tp :read $HOME/.vim/boilerplates/c<cr>kdd<cr>/{<cr>:nohl<cr>o

"preserve folding in files
autocmd BufWinLeave * mkview!
autocmd BufWinEnter * silent loadview

"jk in insert mode will map to <esc>
inoremap jk <esc>
