#!/usr/bin/env bash

icon="lock-red.png"
tmpbg="/tmp/screen.png"

(( $# )) && { icon=$1; }

scrot "$tmpbg"
#convert "$tmpbg" -scale 20% -scale 500% "$tmpbg"
#convert "$tmpbg" "$icon" -gravity center -composite -matte "$tmpbg"
convert "$tmpbg" -blur 0x4 "$tmpbg"
i3lock -i "$tmpbg"
#i3lock -u -i "$tmpbg"
